### ISSUE TITLE
Support GHC 9.8

### ISSUE THREAD

**Issue by ulysses4ever** [tsurucapital/vector-th-unbox#14]
Needs, at least, bumping base and template-haskell bounds.

/Cc @andreasabel who added support for the previous GHC release (9.6).

**Comment by pacak** [comment]
Pull request for that is already there, just need to poke @fumieval to merge/publish it.

**Comment by ulysses4ever** [comment]
Thanks, I missed that! For the reference, it’s #13.

**Comment by andreasabel** [comment]
Revision has been published.

**Comment by ulysses4ever** [comment]
Awesome sauce!!!

**Comment by andreasabel** [comment]
Closed by
- #13.

**Comment by andreasabel** [comment]
@pacak Issue can be closed.
