### ISSUE TITLE
Which GHC versions are supported?

### ISSUE THREAD

**Issue by phadej** [tsurucapital/vector-th-unbox#2]
Based on CI setup, only GHC-8.6+?

**Comment by phadej** [comment]
My wish is that `vector-th-unbox` would support all the version the latest `vector` supports.

**Comment by fumieval** [comment]
I brought back the support for GHC 7.10.3 (and probably some more, I can't test quickly) in vector-th-unbox-0.2.1.9. I updated the CI config and Tested-With accordingly.

**Comment by phadej** [comment]
@fumieval thanks for prompt response

**Comment by phadej** [comment]
The current `master` builds with GHCs down to 7.4.2:

```
                 9.0.1  8.10.3  8.8.4  8.6.5  8.4.4  8.2.2  8.0.2  7.10.3  7.8.4  7.6.3  7.4.2  7.2.2  7.0.4
vector-th-unbox  OK     OK      OK     OK     OK     OK     OK     OK      OK     OK     OK     NO-IP  NO-IP
```

Also tests pass.

**Comment by phadej** [comment]
Feel free to ping me if you have some Haskell-maintenance concerns. I'd like to share what I know/think (instead of doing myself).

I think this issue is resolved. Closing.
