### ISSUE TITLE
Build failures with GHC < 8

### ISSUE THREAD

**Issue by sjakobi** [tsurucapital/vector-th-unbox#7]
See https://matrix.hackage.haskell.org/#/package/vector-th-unbox

For 7.10.3, the error is

```
Data/Vector/Unboxed/Deriving.hs:4:14:
    Unsupported extension: TemplateHaskellQuotes
```

**Comment by pacak** [comment]
Due to https://github.com/tsurucapital/vector-th-unbox/commit/a06a865a5a7d950ea5954b4b51ca6c96a9d94c46, I don't think this support is coming back.

**Comment by sjakobi** [comment]
I don't really have an opinion on which GHC versions this package supports. I just encountered this issue in a package that depends on `vector-th-unbox` via `criterion` (via `statistics`).

In any case, could you tighten the lower bound on `base` for v0.2.2 with a Hackage revision?

**Comment by pacak** [comment]
Sounds like a good idea, will do.

**Comment by sjakobi** [comment]
Thanks for the revision! :)

**Comment by phadej** [comment]
FYI, you can add `other-extensions: TemplateHaskellQuotes` (in revision!) and it would had similar effect, but were semantically more correct.

**Comment by phadej** [comment]
@sjakobi as you are a Hackage Trustee, don't hesitate to make revisions yourself, especially it's in version which solver picks up eagerly (i.e. latest ones) and e.g. breaks some other packages CI etc. (= that's our job).
